baseurl = "/"
languageCode = "en-us"
title = "Casper Theme"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-53280316-2"
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Personal site of Jon Vinson"
  cover = "images/cover.jpg"
  author = "Jon Vinson"
  authorlocation = "Coppell, Texas"
  authorwebsite = "http://jonvinson.info"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-53280316-2"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "electricvino"
  twitterName = "silvervino"
  # facebookName = "jon.b.vinson"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
